### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by MatejVykoukal** [actum/aria-hooks#33]
Create issue templates for bug reports, feature proposals, etc.

@zmrhaljiri Please can you pick this issue or provide @MatejVykoukal with the rights to do that. Currently, It is not possible for me to create issue templates.

**Comment by zmrhaljiri** [comment]
@MatejVykoukal you now have admin rights for this repository, you should be able to do it under the [settings](https://github.com/actum/aria-hooks/settings) :)
